SELECT 
    A.PRODUCT_ID,
    A.PRODUCT_NAME,
    SUM(A.PRICE * IFNULL(B.AMOUNT, 0)) AS TOTAL_SALES
FROM 
    FOOD_PRODUCT A
LEFT JOIN 
    FOOD_ORDER B
ON 
    A.PRODUCT_ID = B.PRODUCT_ID
    AND YEAR(B.PRODUCE_DATE) = 2022
    AND MONTH(B.PRODUCE_DATE) = 5
GROUP BY 
    A.PRODUCT_NAME
HAVING 
    TOTAL_SALES > 0
ORDER BY 
    TOTAL_SALES DESC,
    A.PRODUCT_ID ASC;